theme = "tokyonight_armmy"
[keys.normal]
C-s = "increment"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-t = ":toggle file-picker.git-ignore"

[editor.file-picker]
hidden = false

# C-s = ":w"
